name: travel-insight-api

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      # The version of the Ruby action is setup based on the guide for Ruby versioning (see https://github.com/ruby/setup-ruby#versioning)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.3
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    
    - name: Run build
      run: bundle exec middleman build
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        keep_files: false
        enable_jekyll: true
